"""Seeding 226 unit usaha / cabang lokasi penempatan kandidat."""

import uuid
from .common import now_iso
from ..db import db

DEFAULT_UNITS = (
    "Toserba pusat lt 1",
    "Toserba pusat lt 2",
    "Toserba pusat lt 3 Ahwarumi F.",
    "Online Shop",
    "Ahwarumi Beautycare",
    "Toserba Pondok Putra",
    "Toserba Pondok Putri",
    "Toserba Glagah",
    "Toserba Kalitengah",
    "Toserba Sekapuk",
    "Toserba Palang",
    "Toserba Babat",
    "Toserba Montong",
    "Toserba Sukodadi",
    "Toserba Karangbinagun",
    "Toserba Soko Glagah",
    "Toserba Maduran",
    "Toserba Ngimbang",
    "Toserba Imaan",
    "Toserba Lasem",
    "Toserba Payaman",
    "Toserba Soko Tuban",
    "Toserba Karanggeneng",
    "Toserba Banjarmadu",
    "Toserba Karangtumpuk",
    "Toserba Sekaran",
    "Toserba Temandang",
    "Toserba Merakurak",
    "Toserba Jenu",
    "Toserba Sidayu",
    "Toserba Sembayat",
    "Toserba Modo",
    "Toserba Jatirogo",
    "Toserba Dander",
    "Toserba Padangan",
    "Toserba Tikung",
    "Toserba Bancar",
    "Toserba Telanak",
    "Toserba Banjarejo",
    "Toserba Brondong 1",
    "Toserba PP Miftachussunnah",
    "Toserba Lowayu",
    "Toserba Karanglangit",
    "Toserba Tlogoagung",
    "Toserba Mrican",
    "Toserba Kebomas",
    "Toserba Nguwok",
    "Toserba Tunah",
    "Toserba Parengan",
    "Toserba Padang Bandung",
    "Toserba Paciran 1",
    "Toserba Tambakboyo",
    "Toserba Paciran 2",
    "Toserba Karangagung",
    "Toserba Balongpanggang",
    "Toserba Mojopetung",
    "Toserba Sugio",
    "Toserba Rengel",
    "Toserba Sedayulawas",
    "Toserba Golokan",
    "Toserba Kerek",
    "Toserba Tikung 2",
    "Toserba Sukobendu",
    "Toserba Brondong 2",
    "Toserba Turi",
    "Toserba Wadeng",
    "Toserba Mantup",
    "Toserba Babaksari",
    "Toserba Simo",
    "Toserba Dibe",
    "Toserba Soko Glagah 2",
    "Toserba Pambon",
    "Toserba Petiyen",
    "Toserba Kembangbahu",
    "Toserba Sugio 2",
    "Toserba Gaji",
    "Toserba Sidomukti",
    "Toserba Gesikharjo",
    "Toserba Bumdesma Balongpanggang",
    "Toserba Babatan Mantup",
    "Toserba MWC NU Rengel",
    "Toserba MWC NU Solokuro",
    "Toserba MWC NU Purwosari",
    "Toserba Kembangan",
    "Toserba Mondokan",
    "Toserba Maibit",
    "Toserba Balen",
    "Toserba Kedungsantren",
    "Toserba Sumberwudi",
    "Toserba Kepohbaru",
    "Toserba Ujung Pangkah",
    "Toserba Menganti",
    "Toserba Dalegan",
    "Toserba Sedati",
    "Toserba Sukomulyo",
    "Toserba Kabuh",
    "Toserba Made",
    "Toserba Jatirogo 2",
    "Kdmp Sendangagung",
    "Kdmp Sukodadi",
    "Kdmp Sungegeneng",
    "Kdmp Sekaran",
    "Kdmp Canditunggal",
    "Kdmp Jatirenggo",
    "Kdmp Sukorame",
    "Kdmp Cangkring",
    "Kdmp Mojorejo",
    "Kdmp Kawistolegi",
    "Kdmp Klagensrampat",
    "Kdmp Tunggul",
    "Kdmp Tambakrigadung",
    "Kdmp Guminingrejo",
    "Kdmp Songowareng",
    "Kdmp Deketagung",
    "Kdmp Karanggeneng",
    "Kdmp Kebalankulon",
    "Kdmp Blajo",
    "Kdmp Balongpanggang",
    "Kdmp Randuboto",
    "Kdmp Ngino",
    "Kdmp Karanglo",
    "Kdmp Tambakploso",
    "Kdmp Sidomulyo",
    "Kdmp Pangkatrejo",
    "Kdmp Baron",
    "Kdmp Bulutengger",
    "Kdmp Plososetro",
    "Kdmp Sokosari",
    "Kdmp Saringembat",
    "Kdmp Lajokidul",
    "Kdmp Kelurahanbrondong",
    "Kdmp Gedangan",
    "Kdmp Bringin",
    "Kdmp Guwoterus",
    "Kdmp Gadon",
    "Kdmp Mander",
    "Kdmp Kedungmulyo",
    "Kdmp Boncong",
    "Kdmp Sugihan",
    "Kdmp Simbatan",
    "Kdmp Kranji",
    "Kdmp Lowayu",
    "Kdmp Bulangan",
    "Kdmp Kemangi",
    "Kdmp Surowiti",
    "Kdmp Tracal",
    "Kdmp Sokoglagah",
    "Kdmp Bangeran",
    "Kdmp Tebuwung",
    "Kdmp Serah",
    "Kdmp Kendal",
    "Kdmp Besur",
    "Kdmp Dukuhagung",
    "Kdmp Sidobinangun",
    "Kdmp Indro",
    "Kdmp Putatlor",
    "Kdmp Pakel",
    "Kdmp Tawaran",
    "Kdmp Ngrojo",
    "Kdmp Tuwirikulon",
    "Kdmp Wolutengah",
    "Kdmp Jenggolo",
    "Kdmp Kedaton",
    "Kdmp Klampok",
    "Kdmp Nguluhan",
    "Kdmp Manjung",
    "Kdmp Sumurgung",
    "Kdmp Talun",
    "Kdmp Margosuko",
    "Kdmp Kayen",
    "Kdmp Mergosari",
    "Kdmp Dagangan",
    "Kdmp Pandanagung",
    "Kdmp Gesikan",
    "Kdmp Sidomukti",
    "Kdmp Giri",
    "Kdmp Dahanrejo",
    "Kdmp Sukodono",
    "Kdmp Sukosongo",
    "Kdmp Laren",
    "Kdmp Gempoltukmloko",
    "Kdmp Cangaan",
    "Kdmp Sekarkurung",
    "Kdmp Prambangan",
    "Kdmp Sumberdadi",
    "Kdmp Sumberbendo",
    "Kdmp Mantup",
    "Kdmp Mojosari",
    "Kdmp Keting",
    "Kdmp Kedungkumpul",
    "Kdmp Kertosono",
    "Kdmp Klangonan",
    "Kdmp Lasem",
    "Kdmp Kedanyang",
    "Kdmp Latsari",
    "Kdmp Sendang",
    "Kdmp Karang",
    "Kdmp Payaman",
    "Toko buku dan FC",
    "DDI",
    "Penjualan DC",
    "Kantin PA",
    "Kantin PI",
    "Food Court PaPi",
    "Laundry",
    "Percetakan",
    "Barber Shop",
    "Restoran",
    "Hall",
    "Hotel",
    "Sundra Bakery",
    "RMU",
    "Konveksi",
    "GH",
    "Sundra Fresh Food 1",
    "Apotek Sunan Drajat",
    "Optik Sunan Drajat",
    "Playground Sundra",
    "Restoran Sunan Drajat",
    "Peternakan Sapi",
    "Peternakan Ayam",
    "Peternakan Kuda",
    "Perseklin",
    "Sundra Frozen Food",
    "Kantin DC",
)


async def seed_initial_units() -> int:
    existing_docs = await db.reference_items.find({"list": "unit_usaha"}, {"_id": 0, "nama": 1}).to_list(2000)
    existing_names = {d["nama"] for d in existing_docs}
    to_insert = []
    stamp = now_iso()
    for nama in DEFAULT_UNITS:
        if nama not in existing_names:
            to_insert.append({
                "id": str(uuid.uuid4()),
                "list": "unit_usaha",
                "nama": nama,
                "keterangan": "",
                "created_at": stamp,
            })
            existing_names.add(nama)

    if to_insert:
        await db.reference_items.insert_many(to_insert)
        return len(to_insert)
    return 0
